FROM raspbian-oracle_java:1.0
MAINTAINER Seungryong Kim <srkim@nm.gist.ac.kr>

ADD ListeningInputData.jar /

RUN sudo ln -s /opt/jdk1.8.0_60/bin/java /usr/bin/java


#CMD ls -al
#CMD sudo bin/flume-ng agent --conf conf --conf-file conf/flume-conf.properties --name agent -Dflume.root.logger=INFO,console

